version: "2"
services:
    site:
        image: webdevnicolasfourcade/ubuntu-php7.1:latest
        container_name: web
        ports:
            - "8000:80"
        expose:
            - "80"
        volumes:
          - .:/app
